<a href="https://colab.research.google.com/github/Max010702/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [95]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [96]:
import pandas as pd

In [97]:
print(pd.__version__)

2.2.3

In [98]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Ford", "BMW"],
  'passings': [3, 7, 2, 8, 1, 9, 3]
}

df = pd.DataFrame(mydataset)
print(df)

      cars  passings
0      BMW         3
1    Volvo         7
2     Ford         2
3    Tesla         8
4  Ferrari         1
5     Ford         9
6      BMW         3

In [99]:
df.head() # default 5 rows

      cars  passings
0      BMW         3
1    Volvo         7
2     Ford         2
3    Tesla         8
4  Ferrari         1

In [100]:
df.tail() # default 5 rows

      cars  passings
2     Ford         2
3    Tesla         8
4  Ferrari         1
5     Ford         9
6      BMW         3

In [101]:
df.shape

(7, 2)

In [102]:
df.columns

Index(['cars', 'passings'], dtype='object')

In [103]:
df.dtypes

cars        object
passings     int64
dtype: object

In [104]:
print(df)

      cars  passings
0      BMW         3
1    Volvo         7
2     Ford         2
3    Tesla         8
4  Ferrari         1
5     Ford         9
6      BMW         3

In [105]:
df.describe() # numerical columns only

       passings
count  7.000000
mean   4.714286
std    3.199702
min    1.000000
25%    2.500000
50%    3.000000
75%    7.500000
max    9.000000

In [106]:
df.iloc[2:]

      cars  passings
2     Ford         2
3    Tesla         8
4  Ferrari         1
5     Ford         9
6      BMW         3

In [107]:
 df.loc[2:5, "cars"]

2       Ford
3      Tesla
4    Ferrari
5       Ford
Name: cars, dtype: object

In [108]:
print(df)

      cars  passings
0      BMW         3
1    Volvo         7
2     Ford         2
3    Tesla         8
4  Ferrari         1
5     Ford         9
6      BMW         3

In [109]:
df[df["cars"] == "Tesla"]

    cars  passings
3  Tesla         8

In [110]:
# df.mean(numeric_only=True)
df["passings"].mean()

np.float64(4.714285714285714)

In [111]:
df.sum()

cars        BMWVolvoFordTeslaFerrariFordBMW
passings                                 33
dtype: object

In [112]:
df.min()

cars        BMW
passings      1
dtype: object

In [113]:
df.max()

cars        Volvo
passings        9
dtype: object

In [114]:
df.median(numeric_only=True)

passings    3.0
dtype: float64

In [115]:
df.count()

cars        7
passings    7
dtype: int64

In [116]:
df.std(numeric_only=True)

passings    3.199702
dtype: float64

In [117]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Ford"],
    "counts": [3, 7, None, 8, 1, 9, None]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6     Ford     NaN

In [118]:
df_missing.isnull()

    cars  counts
0  False   False
1  False   False
2   True    True
3  False   False
4  False   False
5   True   False
6  False    True

In [119]:
df_missing.isnull().sum()

cars      2
counts    2
dtype: int64

In [120]:
df_missing.dropna(subset=['cars'])

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
6     Ford     NaN

In [125]:
df_missing.fillna({"cars": "unknown", "counts": 0})

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6     Ford     0.0

In [135]:
# df = pd.read_csv("Titanic-Dataset.csv")


df = pd.read_excel("test.xlsx")

df.tail()

# df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [136]:
df.to_excel("test.xlsx")

In [138]:
# Series => 1D
cars = pd.Series(["BMW", "Tesla", "Ferrari"])
print(cars)

0        BMW
1      Tesla
2    Ferrari
dtype: object

In [140]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Ford']